language: python

cache:
  - pip
  - directories:
  - .tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

script: tox
